# Generated by Django 3.1.6 on 2021-06-01 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storage',
            old_name='link',
            new_name='link_path',
        ),
    ]
