# Generated by Django 3.1.6 on 2021-06-15 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='cover',
            field=models.ImageField(blank=True, default='assets/default-img.jpg', upload_to='assets/'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='cover_url',
            field=models.CharField(blank=True, default='assets/default-img.jpg', max_length=500),
        ),
    ]
